CREATE TABLE IF NOT EXISTS rooms (
  id UUID PRIMARY KEY,
  number VARCHAR(3) UNIQUE NOT NULL,
  type VARCHAR(50) NOT NULL,
  capacity INTEGER NOT NULL,
  price INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);